export const FETCH_VEGETABLES_BEGIN = "FETCH_VEGETABLES_BEGIN";
export const FETCH_VEGETABLES_SUCCESS = "FETCH_VEGETABLES_SUCCESS";
export const FETCH_VEGETABLES_FAILURE = "FETCH_VEGETABLES_FAILURE";

export const FETCH_MEAT_BEGIN = "FETCH_MEAT_BEGIN";
export const FETCH_MEAT_SUCCESS = "FETCH_MEAT_SUCCESS";
export const FETCH_MEAT_FAILURE = "FETCH_MEAT_FAILURE";

export const FETCH_OTHER_BEGIN = "FETCH_OTHER_BEGIN";
export const FETCH_OTHER_SUCCESS = "FETCH_OTHER_SUCCESS";
export const FETCH_OTHER_FAILURE = "FETCH_OTHER_FAILURE";

export const INGREDIENT_ADD = "INGREDIENT_ADD";
export const INGREDIENT_REMOVE = "INGREDIENT_REMOVE";

export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAILURE = "FETCH_RECIPES_FAILURE";

export const RECIPE_FILTER_SUCCESS = "RECIPE_FILTER_SUCCESS";
